language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode
#  - rbx-19mode
branches:
  only:
    - 'master'
gemfile: src/qubar.site/Gemfile
script: bundle exec rake -f src/qubar.site/rakefile
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec