language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
#  - 1.9.2
#  - 1.8.7
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode
#  - rbx-19mode 
branches:
  only:
    - 'master'
gemfile:
  - Gemfile
before_script:
  - sh vendor/bin/install_console_audio_tools.sh
script:
#  - ls -la
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake --trace
notifications:
  webhooks: http://build.ecosounds.org/build